### ISSUE TITLE
Restrict access to /rorvswild

### ISSUE THREAD

**Issue by vitobotta** [BaseSecrete/rorvswild#11]
Hi! I am currently testing the service and have an app deployed to Kubernetes for dev/staging/prod environments. I am using Telepresence for development, so the app can run in development mode as well which means that the /rorvswild path is accessible to everyone. Is it possible to make sure that only e.g. admins can see it or disable it altogether? 

Thanks!

**Comment by alexisbernard** [comment]
Hi, if your are interested in production monitoring only you can disable the locale profiling. Simply add this line in an initializer : `Rails.application.config.middleware.delete(RorVsWild::Local::Middleware)`

For adding authentication I have to update the gem.

**Comment by vitobotta** [comment]
Hi @alexisbernard - have you had a chance to add authentication for local profiling? Thanks
