### ISSUE TITLE
Connection error when trying to report

### ISSUE THREAD

**Issue by Roko131** [BaseSecrete/rorvswild#14]
We encountered the following error, seem to originate from rorvswild.
Reports have stopped reaching

We tried with ruby 2.5.3 as well, same results.

`rorvswild 1.5.5`
`Ruby 2.7.1`
`Rails 5.2.4.3`
`nginx/1.19.0`
`Phusion Passenger 6.0.2`

      01 2020-05-31 16:19:01.399491 E [122091:119660 client.rb:63] Rails -- /home/my_user/.rbenv/versions/2.7.1/lib/ruby/2.7.0/net/protocol.rb:44:in `connect_nonblock': SSL_connect returned=1 errno=0 state=error: certificate verify failed (certificate has expired) (OpenSSL::SSL::SSLError)
      01 	from /home/my_user/.rbenv/versions/2.7.1/lib/ruby/2.7.0/net/protocol.rb:44:in `ssl_socket_connect'
      01 	from /home/my_user/.rbenv/versions/2.7.1/lib/ruby/2.7.0/net/http.rb:1009:in `connect'
      01 	from /home/my_user/.rbenv/versions/2.7.1/lib/ruby/2.7.0/net/http.rb:943:in `do_start'
      01 	from /home/my_user/.rbenv/versions/2.7.1/lib/ruby/2.7.0/net/http.rb:932:in `start'
      01 	from /home/my_user/.rbenv/versions/2.7.1/lib/ruby/2.7.0/net/http.rb:1483:in `request'
      01 	from /home/my_user/domains/my-domain.com/app/shared/bundle/ruby/2.7.0/gems/rorvswild-1.5.5/lib/rorvswild/plugin/net_http.rb:27:in `block in request_with_rorvswild'
      01 	from /home/my_user/domains/my-domain.com/app/shared/bundle/ruby/2.7.0/gems/rorvswild-1.5.5/lib/rorvswild/agent.rb:55:in `measure_section'
      01 	from /home/my_user/domains/my-domain.com/app/shared/bundle/ruby/2.7.0/gems/rorvswild-1.5.5/lib/rorvswild/plugin/net_http.rb:26:in `request_with_rorvswild'
      01 	from /home/my_user/domains/my-domain.com/app/shared/bundle/ruby/2.7.0/gems/rorvswild-1.5.5/lib/rorvswild/plugin/net_http.rb:18:in `request'
      01 	from /home/my_user/domains/my-domain.com/app/shared/bundle/ruby/2.7.0/gems/rorvswild-1.5.5/lib/rorvswild/client.rb:60:in `transmit'
      01 	from /home/my_user/domains/my-domain.com/app/shared/bundle/ruby/2.7.0/gems/rorvswild-1.5.5/lib/rorvswild/client.rb:33:in `post'
      01 	from /home/my_user/domains/my-domain.com/app/shared/bundle/ruby/2.7.0/gems/rorvswild-1.5.5/lib/rorvswild/queue.rb:61:in `flush'
      01 	from /home/my_user/domains/my-domain.com/app/shared/bundle/ruby/2.7.0/gems/rorvswild-1.5.5/lib/rorvswild/queue.rb:54:in `flush_indefinetely'
      01 	from /home/my_user/domains/my-domain.com/app/shared/bundle/ruby/2.7.0/gems/rorvswild-1.5.5/lib/rorvswild/queue.rb:67:in `block in start_thread'

**Comment by alexisbernard** [comment]
It's because the AdTrust root CA has expired on the 30th may. A good explanation can been found here https://www.agwa.name/blog/post/fixing_the_addtrust_root_expiration.

I would be interested to to know the version of your OS in order to have an idea of the impact of affected users.

I have updated the certificate chain to solve the issue. Let me know if everything is fine on your side.

**Comment by Roko131** [comment]
Now it works- Thanks.

Using `CentOS 7`

**Comment by alexisbernard** [comment]
Thanks for the feedback.
