### ISSUE TITLE
WebSocket error

### ISSUE THREAD

**Issue by skyporter** [BaseSecrete/rorvswild#16]
The local render raise an error when using WebSocket (through StimulusReflex in my case): 

> StimulusReflex::Channel Failed to re-render http://localhost:3000 undefined method `[]=' for nil:NilClass .../gems/rorvswild-1.5.2/lib/rorvswild/plugin/action_controller.rb:16:in `start'

On the other hand, is there a way to turn off local rendering?

**Comment by alexisbernard** [comment]
It has been fixed in version 1.5.4, but the latest is 1.5.6  ;-)

**Comment by skyporter** [comment]
oh! sorry for that! I'll update the gem. Thanks!
