### ISSUE TITLE
Documentation / Readme / Installation procedure problem

### ISSUE THREAD

**Issue by zedalaye** [BaseSecrete/rorvswild#2]
To start/configure RorVsWild from an initializer, the code to use with v1.0.0 is :

```ruby
RorVsWild.start(api_key: 'TheRorVsWildAppKey')
```

instead of `RorVsWild::Client.new(api_key: 'TheRorVsWildAppKey')`

**Comment by alexisbernard** [comment]
Thanks, I updated the instructions.
