### ISSUE TITLE
Error: undefined method `process' for class `Redis::Client'

### ISSUE THREAD

**Issue by wscourge** [BaseSecrete/rorvswild#21]
Upon `bundle exec rails server`, I receive:

> => Booting Puma
> => Rails 7.0.4 application starting in development
> => Run `bin/rails server --help` for more startup options
> Exiting
> /usr/local/bundle/gems/rorvswild-1.5.16/lib/rorvswild/plugin/redis.rb:8:in `alias_method': undefined method `process' for class `Redis::Client' (NameError)
>
>           alias_method :process_without_rorvswild, :process
>           ^^^^^^^^^^^^
> Did you mean?  proc

<details>
  <summary>Stacktrace</summary>
  <pre>
  Did you mean?  proc
  	from /usr/local/bundle/gems/rorvswild-1.5.16/lib/rorvswild/plugin/redis.rb:8:in `block in setup'
  	from /usr/local/bundle/gems/rorvswild-1.5.16/lib/rorvswild/plugin/redis.rb:7:in `class_eval'
  	from /usr/local/bundle/gems/rorvswild-1.5.16/lib/rorvswild/plugin/redis.rb:7:in `setup'
  	from /usr/local/bundle/gems/rorvswild-1.5.16/lib/rorvswild/agent.rb:50:in `block in setup_plugins'
  	from /usr/local/bundle/gems/rorvswild-1.5.16/lib/rorvswild/agent.rb:46:in `each'
  	from /usr/local/bundle/gems/rorvswild-1.5.16/lib/rorvswild/agent.rb:46:in `setup_plugins'
  	from /usr/local/bundle/gems/rorvswild-1.5.16/lib/rorvswild/agent.rb:35:in `initialize'
  	from /usr/local/bundle/gems/rorvswild-1.5.16/lib/rorvswild.rb:12:in `new'
  	from /usr/local/bundle/gems/rorvswild-1.5.16/lib/rorvswild.rb:12:in `start'
  	from /usr/local/bundle/gems/rorvswild-1.5.16/lib/rorvswild/local.rb:8:in `start'
  	from /usr/local/bundle/gems/rorvswild-1.5.16/lib/rorvswild/rails_loader.rb:17:in `start'
  	from /usr/local/bundle/gems/rorvswild-1.5.16/lib/rorvswild/rails_loader.rb:6:in `block in start_on_rails_initialization'
  	from /usr/local/bundle/gems/railties-7.0.4/lib/rails/initializable.rb:32:in `instance_exec'
  	from /usr/local/bundle/gems/railties-7.0.4/lib/rails/initializable.rb:32:in `run'
  	from /usr/local/bundle/gems/railties-7.0.4/lib/rails/initializable.rb:61:in `block in run_initializers'
  	from /usr/local/lib/ruby/3.1.0/tsort.rb:228:in `block in tsort_each'
  	from /usr/local/lib/ruby/3.1.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
  	from /usr/local/lib/ruby/3.1.0/tsort.rb:431:in `each_strongly_connected_component_from'
  	from /usr/local/lib/ruby/3.1.0/tsort.rb:349:in `block in each_strongly_connected_component'
  	from /usr/local/lib/ruby/3.1.0/tsort.rb:347:in `each'
  	from /usr/local/lib/ruby/3.1.0/tsort.rb:347:in `call'
  	from /usr/local/lib/ruby/3.1.0/tsort.rb:347:in `each_strongly_connected_component'
  	from /usr/local/lib/ruby/3.1.0/tsort.rb:226:in `tsort_each'
  	from /usr/local/lib/ruby/3.1.0/tsort.rb:205:in `tsort_each'
  	from /usr/local/bundle/gems/railties-7.0.4/lib/rails/initializable.rb:60:in `run_initializers'
  	from /usr/local/bundle/gems/railties-7.0.4/lib/rails/application.rb:372:in `initialize!'
  	<b>from /app/config/environment.rb:16:in &lt;main&gt;'</b>
  	from config.ru:5:in `require_relative'
  	from config.ru:5:in `block in <main>'
  	from /usr/local/bundle/gems/rack-2.2.4/lib/rack/builder.rb:116:in `eval'
  	from /usr/local/bundle/gems/rack-2.2.4/lib/rack/builder.rb:116:in `new_from_string'
  	from /usr/local/bundle/gems/rack-2.2.4/lib/rack/builder.rb:105:in `load_file'
  	from /usr/local/bundle/gems/rack-2.2.4/lib/rack/builder.rb:66:in `parse_file'
  	from /usr/local/bundle/gems/rack-2.2.4/lib/rack/server.rb:349:in `build_app_and_options_from_config'
  	from /usr/local/bundle/gems/rack-2.2.4/lib/rack/server.rb:249:in `app'
  	from /usr/local/bundle/gems/rack-2.2.4/lib/rack/server.rb:422:in `wrapped_app'
  	from /usr/local/bundle/gems/railties-7.0.4/lib/rails/commands/server/server_command.rb:76:in `log_to_stdout'
  	from /usr/local/bundle/gems/railties-7.0.4/lib/rails/commands/server/server_command.rb:36:in `start'
  	from /usr/local/bundle/gems/railties-7.0.4/lib/rails/commands/server/server_command.rb:143:in `block in perform'
  	from <internal:kernel>:90:in `tap'
  	from /usr/local/bundle/gems/railties-7.0.4/lib/rails/commands/server/server_command.rb:134:in `perform'
  	from /usr/local/bundle/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
  	from /usr/local/bundle/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
  	from /usr/local/bundle/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
  	from /usr/local/bundle/gems/railties-7.0.4/lib/rails/command/base.rb:87:in `perform'
  	from /usr/local/bundle/gems/railties-7.0.4/lib/rails/command.rb:48:in `invoke'
  	from /usr/local/bundle/gems/railties-7.0.4/lib/rails/commands.rb:18:in `<main>'
  	from /usr/local/bundle/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
  	from /usr/local/bundle/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
  	from bin/rails:4:in `<main>'
  sqlite_rollup_app exited with code 1
  </pre>
  <p>The bolded <b>from /app/config/environment.rb:16</b> points to line 16 code that in my case is the standard <code>Rails.application.initialize!</code> call. File is longer due to the Rollbar initialization being present there, and is not relevant to this issue.</p>
</details>

**Gemfile versions**:

```
ruby '3.1.2'
gem 'rails', '~> 7.0'
gem 'redis', '~> 5.0'
gem 'rorvswild', '~> 1.5'
```

**Comment by alexisbernard** [comment]
Thanks for all the details. I have prepared a fix that you can use by updating your Gemfile :

```ruby
gem "rorvswild", git: "https://github.com/BaseSecrete/rorvswild.git", ref: "463218e40dde8e22bfd1eda8a2e3cc532800c375"
```

Before releasing a new version, I still have some work to keep monitoring Redis' pipelines. I will write here once, it's done.

**Comment by wscourge** [comment]
Thank you. Feel free to close the issue whenever it is released
