### ISSUE TITLE
Add keyboard support for closing breakdown dialog

### ISSUE THREAD

**Issue by ledermann** [BaseSecrete/rorvswild#25]
Currently, the breakdown dialog in development mode can be closed by clicking on the `X`-Button or by clicking on the toggle button again. 

How about adding keyboard support? I would prefer to close the dialog by pressing <kbd>ESC</kbd>.

**Comment by alexisbernard** [comment]
It has been added in 999f13f3476b04d0a05c2647bef308c77f845820.

**Comment by ledermann** [comment]
Works fine, thanks!

**Comment by alexisbernard** [comment]
The version 1.6.4 has been released.
