### ISSUE TITLE
Rails 3 Support.

### ISSUE THREAD

**Issue by joshuapinter** [BaseSecrete/rorvswild#4]
I got this error when trying to use RoRvsWild: 

```bash
NoMethodError: undefined method `around_action' for ActionController::Base:Class
```

Looks like that method was introduced in Rails 4. 

Do you have a Rails 3-compatible version of the gem? We'd still like to make sure of the performance monitoring service.

Thanks!

**Comment by alexisbernard** [comment]
There is no Rails 3 compatible gem, sorry.
