### ISSUE TITLE
Cannot load Sidekiq WebUI with RoRvsWild gem v1.3

### ISSUE THREAD

**Issue by zedalaye** [BaseSecrete/rorvswild#5]
Don't know why but the sidekiq WebUI don't load when RorvsWild is upgraded to v1.3. I had to downgrade to v < 1.3 to make Sidekiq WebUI load again (in development)

**Comment by alexisbernard** [comment]
Thanks, I will investigate.

**Comment by alexisbernard** [comment]
It has been fixed in 1.3.1 ;-)
