### ISSUE TITLE
RuntimeError: can't modify frozen String

### ISSUE THREAD

**Issue by ug0** [BaseSecrete/rorvswild#6]
Ruby: 2.4.2p198
Rails: Rails 5.2.0.beta2

I got this error in my Rails app when create, update, destroy records in controller actions. After I removed 'rorvswild' gem the issue disappeared.

I've created a [repo](https://github.com/ug0/rorvswild_app) has the same Gemfile as my actual app. I've cloned and tried the repo, confirmed I can reproduce the issue with it.

Steps to reproduce:

1. Clone the [repo](https://github.com/ug0/rorvswild_app).
2. Rails set up stuff, bundle install, db:create, db:migrate.
3. Launch the server.
4. Visit localhost:3000/posts, try to create/edit/delete posts, you should get the same error.

**Comment by alexisbernard** [comment]
Thanks for the bug report. I fixed it and released a new version. Update your Gemfile:

```
gem "rorvswild", "~> 1.3.2"
```
