### ISSUE TITLE
#<Encoding::CompatibilityError: incompatible character encodings: ASCII-8BIT and UTF-8>

### ISSUE THREAD

**Issue by jazzdragon** [BaseSecrete/rorvswild#8]
Hi,
Just updated from 1.1.1 to 1.3.4 and getting this error:
![image](https://user-images.githubusercontent.com/5546798/36394963-818744fc-156b-11e8-89f7-47ae485560df.png)

**Comment by alexisbernard** [comment]
Thanks for the bug report. I just fixed it in version 1.3.5 :)
